-- 一時的にRLSを無効にしてテスト

ALTER TABLE drivers DISABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles DISABLE ROW LEVEL SECURITY;
ALTER TABLE routes DISABLE ROW LEVEL SECURITY;
ALTER TABLE destinations DISABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_details DISABLE ROW LEVEL SECURITY;